### ISSUE TITLE
Conflict with wrap plugin - <WRAP noprint>... </WRAP> doesn't work

### ISSUE THREAD

**Issue by Chris75forumname** [ssahara/dw-plugin-NumberedHeadings#19]
Wrapping of numbered sections with the wrap plugin, such as `<WRAP noprint> ... </WRAP>` is broken. Closing tags get lost.
I guess this is not intended. For now, I found a workaround. Just double-wrap, like so:

```
<WRAP noprint>
<WRAP noprint>
===== - Heading title =====
// my content //
==== - sub heading ====
// etc //
</WRAP>
</WRAP>
```

**Comment by ssahara** [comment]
Thanks. It helped me to find that function `getPType()` has been missing. I hope new version 2023-09-12 should fix this issue.
