### ISSUE TITLE
Compatibility with Hrun

### ISSUE THREAD

**Issue by lyynxx** [ssahara/dw-plugin-NumberedHeadings#5]
Hi, 

on my old setup with DokuWiki release Hrun and PHP 5.5, the plugin failed to load. This is due to the null coalescing operator ?? (only added in PHP 7.0) used in syntax.php. May I suggest to replace the operator with the ternary operator? This change makes the plugin compatible with older versions.

**Comment by ssahara** [comment]
Hi,
I have been working to refactor the plugin. The plugin release 2019-08-24, in which null coalescing operators are not used, should work with older PHP 5.  I could not test with PHP 5 and appreciate it if you could report whether new version has worked with old PHP or not. 
Please note that you may need to adjust plugin config parameters in the configuration manager.

**Comment by lyynxx** [comment]
Hi, 

again a small problem: PHP 5 does not support these assignments: 
[$el1, $el2] = ...
Line 93: [$number, $title] = ['', trim($text)];
Line 107:  [$number, $title] = explode(' ', substr($text, 1), 2);

After rewriting these two lines, the plugin works fine.

**Comment by ssahara** [comment]
Thanks, @lyynxx 
Please see 741794df261c5c441a4605fd339957c558c06098 [PHP 5] use list() to assign variables

**Comment by lyynxx** [comment]
Thanks for the support @ssahara
Now it works fine.

**Comment by lyynxx** [comment]
Thanks for the support @ssahara
Now it works fine.
